#!/usr/bin/env python3
"""Check the README cohort against live GitHub repository metadata.

The selection audit admits a project on four rules, three of which are facts
that drift: license, recorded activity and star count. Maintaining those by
hand guarantees they are wrong within days of publication, so this script reads
them from the GitHub API and compares them with the recorded snapshot.

    python3 tools/visibility_check.py            # verify; nonzero on violation
    python3 tools/visibility_check.py --refresh  # rewrite the snapshot table

Eligibility violations — archived, unlicensed, stale, or below the star
threshold — fail the check, because they change which projects belong in the
cohort. Star drift alone only warns: the number is a coarse attention signal,
and a snapshot is allowed to age between refreshes.

Set `GITHUB_TOKEN` to raise the API rate limit. Without it the script still
runs, at 60 requests per hour per IP.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "docs" / "validation" / "visibility-snapshot.json"
AUDIT = ROOT / "docs" / "validation" / "popular-harness-selection.md"

STAR_THRESHOLD = 30_000
ACTIVITY_WINDOW = timedelta(days=182)
#: Star drift beyond this fraction means the published snapshot is misleading.
DRIFT_TOLERANCE = 0.10

TABLE_START = "<!-- visibility:start -->"
TABLE_END = "<!-- visibility:end -->"


def fetch(repo: str) -> dict[str, object]:
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}",
        headers={"Accept": "application/vnd.github+json", "User-Agent": "4c-harness"},
    )
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def live_facts(repo: str) -> dict[str, object]:
    data = fetch(repo)
    license_block = data.get("license") or {}
    return {
        "stars": data["stargazers_count"],
        "license": license_block.get("spdx_id") or "NONE",
        "pushed_at": data["pushed_at"],
        "archived": bool(data["archived"]),
    }


def check(entry: dict[str, object], live: dict[str, object], now: datetime) -> tuple[list[str], list[str]]:
    """Return (eligibility violations, drift warnings) for one project."""
    repo = entry["repo"]
    violations: list[str] = []
    warnings: list[str] = []

    if live["archived"]:
        violations.append(f"{repo}: archived; fails the current-relevance rule")
    if live["stars"] < STAR_THRESHOLD:
        violations.append(
            f"{repo}: {live['stars']:,} stars is below the {STAR_THRESHOLD:,} threshold"
        )
    pushed = datetime.fromisoformat(live["pushed_at"].replace("Z", "+00:00"))
    if now - pushed > ACTIVITY_WINDOW:
        violations.append(f"{repo}: no recorded activity since {pushed.date()}")
    if live["license"] != entry["license"]:
        violations.append(
            f"{repo}: license is {live['license']}, recorded as {entry['license']}"
        )

    recorded = entry["stars"]
    if recorded and abs(live["stars"] - recorded) / recorded > DRIFT_TOLERANCE:
        warnings.append(
            f"{repo}: recorded {recorded:,} stars, live {live['stars']:,} "
            f"({(live['stars'] - recorded) / recorded:+.0%}); run --refresh"
        )
    return violations, warnings


def render_table(entries: list[dict[str, object]], checked: str) -> str:
    rows = [
        "| Project | Cohort | Approx. stars | License | Last activity |",
        "|---|---|---:|---|---|",
    ]
    for entry in sorted(entries, key=lambda item: (item["cohort"], -item["stars"])):
        rows.append(
            f"| [{entry['name']}](https://github.com/{entry['repo']}) "
            f"| {entry['cohort']} | {entry['stars']:,} | {entry['license']} "
            f"| {entry['pushed_at'][:10]} |"
        )
    rows.append("")
    rows.append(
        f"Generated by `tools/visibility_check.py --refresh` from the GitHub API "
        f"on **{checked}**. Stars determine eligibility only; they never affect a "
        f"4C assessment."
    )
    return "\n".join(rows)


def write_table(entries: list[dict[str, object]], checked: str) -> None:
    text = AUDIT.read_text()
    table = render_table(entries, checked)
    pattern = re.compile(
        f"{re.escape(TABLE_START)}.*?{re.escape(TABLE_END)}", re.DOTALL
    )
    if not pattern.search(text):
        raise SystemExit(f"{AUDIT} is missing the {TABLE_START} markers")
    AUDIT.write_text(pattern.sub(f"{TABLE_START}\n{table}\n{TABLE_END}", text))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="update the snapshot file and the generated audit table",
    )
    args = parser.parse_args()

    snapshot = json.loads(SNAPSHOT.read_text())
    entries = snapshot["projects"]
    now = datetime.now(timezone.utc)

    violations: list[str] = []
    warnings: list[str] = []
    for entry in entries:
        try:
            live = live_facts(entry["repo"])
        except urllib.error.HTTPError as error:
            violations.append(f"{entry['repo']}: GitHub API returned {error.code}")
            continue
        entry_violations, entry_warnings = check(entry, live, now)
        violations.extend(entry_violations)
        warnings.extend(entry_warnings)
        if args.refresh:
            entry.update(live)

    for warning in warnings:
        print(f"WARN  {warning}")
    for violation in violations:
        print(f"FAIL  {violation}", file=sys.stderr)

    if args.refresh:
        checked = now.date().isoformat()
        snapshot["checked"] = checked
        SNAPSHOT.write_text(json.dumps(snapshot, indent=2) + "\n")
        write_table(entries, checked)
        print(f"refreshed {len(entries)} projects at {checked}")

    if violations:
        raise SystemExit(1)
    print(f"cohort eligibility holds for {len(entries)} projects")


if __name__ == "__main__":
    main()
